const RESUMO_PEDIDO = Cypress.env("CENARIOS")["RESUMO_PEDIDO"];
const PEDIDO_AUTOMATICO = Cypress.env("CENARIOS")["PEDIDO_AUTOMATICO"];
const GERACAO_PEDIDO_HOMOL_SEM_CONFIG =
    Cypress.env("CENARIOS")["GERACAO_PEDIDO_HOMOL_SEM_CONFIG"];
const GERACAO_PEDIDO_HOMOL_COM_CONFIG =
    Cypress.env("CENARIOS")["GERACAO_PEDIDO_HOMOL_COM_CONFIG"];
const ENVIO_PEDIDO_HOMOL_SEM_CONFIG =
    Cypress.env("CENARIOS")["ENVIO_PEDIDO_HOMOL_SEM_CONFIG"];
const ENVIO_PEDIDO_HOMOL_COM_CONFIG =
    Cypress.env("CENARIOS")["ENVIO_PEDIDO_HOMOL_COM_CONFIG"];
const PEDIDO_MANUAL = Cypress.env("CENARIOS")["PEDIDO_MANUAL"];
const REVISAO_ENVIO = Cypress.env("CENARIOS")["REVISAO_ENVIO"];
const TESTES_GERAIS = Cypress.env("CENARIOS")["TESTES_GERAIS"];
const GERACAO_PEDIDO_AUTO =
    Cypress.env("CENARIOS")["ESPECIFICOS"]["GERACAO_PEDIDO_AUTO"];
const ENVIO_PEDIDO = Cypress.env("CENARIOS")["ENVIO_PEDIDO"];

const USUARIO_DEMO = Cypress.env("LOGIN")["USUARIO_DEMO"];
const SENHA_DEMO = Cypress.env("LOGIN")["SENHA_DEMO"];
const CLIENTE_USUARIO = Cypress.env("LOGIN")["CLIENTE_USUARIO"];
const CLIENTE_USUARIO_HOMOLOG_SEM_CONFIG =
    Cypress.env("LOGIN")["CLIENTE_USUARIO_HOMOLOG_SEM_CONFIG"];
const CLIENTE_USUARIO_HOMOLOG_COM_CONFIG =
    Cypress.env("LOGIN")["CLIENTE_USUARIO_HOMOLOG_COM_CONFIG"];
const CLIENTE_SENHA = Cypress.env("LOGIN")["CLIENTE_SENHA"];
const USUARIO_AUTH = Cypress.env("LOGIN")["USUARIO_AUTH"];
const SENHA_AUTH = Cypress.env("LOGIN")["SENHA_AUTH"];

const URL_AMPLIFY_DEMO = Cypress.env("URLS")["URL_AMPLIFY_DEMO"];
const URL_AMPLIFY_HOMOLOGACAO = Cypress.env("URLS")["URL_AMPLIFY_HOMOLOGACAO"];
const URL_DEMO = Cypress.env("URLS")["URL_DEMO"];
const URL_AUTH_DEMO = Cypress.env("URLS")["URL_AUTH_DEMO"];
const URL_API_TESTES = Cypress.env("URLS")["URL_API_TESTES"];

const ROTA_COTACAO_EM_ANALISE =
    Cypress.env("URLS")["ROTAS"]["ROTA_COTACAO_EM_ANALISE"];
const ROTA_GET_SITUACAO_PEDIDO_BY_COTACAO =
    Cypress.env("URLS")["ROTAS"]["ROTA_GET_SITUACAO_PEDIDO_BY_COTACAO"];
const ROTA_REINICIAR_COMPLETAMENTE_COTACAO =
    Cypress.env("URLS")["ROTAS"]["ROTA_REINICIAR_COMPLETAMENTE_COTACAO"];

const DB_USER = Cypress.env("DB")["DB_USER"];
const DB_PSSWRD = Cypress.env("DB")["DB_PSSWRD"];
const DB_CONNECT_URL = Cypress.env("DB")["DB_CONNECT_URL"];

export {
    RESUMO_PEDIDO,
    PEDIDO_AUTOMATICO,
    GERACAO_PEDIDO_HOMOL_SEM_CONFIG,
    GERACAO_PEDIDO_HOMOL_COM_CONFIG,
    ENVIO_PEDIDO_HOMOL_SEM_CONFIG,
    ENVIO_PEDIDO_HOMOL_COM_CONFIG,
    PEDIDO_MANUAL,
    REVISAO_ENVIO,
    TESTES_GERAIS,
    GERACAO_PEDIDO_AUTO,
    USUARIO_DEMO,
    SENHA_DEMO,
    CLIENTE_USUARIO,
    CLIENTE_USUARIO_HOMOLOG_SEM_CONFIG,
    CLIENTE_USUARIO_HOMOLOG_COM_CONFIG,
    CLIENTE_SENHA,
    URL_AMPLIFY_DEMO,
    URL_AMPLIFY_HOMOLOGACAO,
    URL_DEMO,
    URL_AUTH_DEMO,
    DB_USER,
    DB_PSSWRD,
    DB_CONNECT_URL,
    ROTA_COTACAO_EM_ANALISE,
    URL_API_TESTES,
    USUARIO_AUTH,
    SENHA_AUTH,
    ENVIO_PEDIDO,
    ROTA_GET_SITUACAO_PEDIDO_BY_COTACAO,
    ROTA_REINICIAR_COMPLETAMENTE_COTACAO,
};
